### ISSUE TITLE
CSS bug in the Usage Examples component

### ISSUE THREAD

**Issue by d2s** [sw-yx/is-this-netlify#3]
Noticed a visual bug in the `Usage Examples` component, located in the [`UsageExample.svelte`](https://github.com/sw-yx/is-this-netlify/blob/695a9359f0f5b813176a8310c1d48a08e56e612e/src/UsageExample.svelte) file.
Issue is caused as link colors are not defined in the `<style>` block of the component, even while background color is adjusted to look different from the rest of the site's color palette.

Lack of visual contrast between the light background color, and white text color.

<img width="551" alt="2020-02-12-is-this netlify com-usage-examples-bug" src="https://user-images.githubusercontent.com/135053/74357310-6dd9a700-4dc8-11ea-9b2e-249e46da589b.PNG">

Text is only visible when selecting it manually.

<img width="420" alt="2020-02-12-is-this netlify com-usage-examples-bug2" src="https://user-images.githubusercontent.com/135053/74357424-92358380-4dc8-11ea-86ce-5c397a5490cc.PNG">

**Comment by swyxio** [comment]
yea think this is a regression from when i tweaked the dark theme a bit. i will fix

**Comment by swyxio** [comment]
not pretty, but fixed 
![image](https://user-images.githubusercontent.com/6764957/74359193-d147e280-4d90-11ea-9879-af77b8e5c3b9.png)

design PR welcome :)
